import type { ServerDefinition } from "../contracts.js";

export const DEFAULT_SERVERS: readonly ServerDefinition[] = [
	{
		id: "typescript",
		roles: ["diagnostics", "semantic", "mutation"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
		languageIds: [
			"typescript",
			"typescriptreact",
			"javascript",
			"javascriptreact",
		],
		command: "typescript-language-server",
		args: ["--stdio"],
		priority: 100,
		autoInstall: true,
		admission: "auto-installable",
		diagnostics: {
			pushGraceMs: 5_000,
			settleMs: 50,
			pullGraceMs: 250,
		},
		compatibility: [
			{
				platform: "win32",
				architecture: "x64",
				runner: "windows-2022",
				nodeVersion: "22.19.0",
				piVersion: "0.84.1",
				serverVersion: "5.3.0",
				languageVersion: "5.9.3",
				capabilities: [
					"diagnostics",
					"definition",
					"references",
					"document-symbols",
					"rename",
					"process-reuse",
					"shutdown",
				],
			},
			{
				platform: "darwin",
				architecture: "arm64",
				runner: "macos-14",
				nodeVersion: "22.19.0",
				piVersion: "0.84.1",
				serverVersion: "5.3.0",
				languageVersion: "5.9.3",
				capabilities: [
					"diagnostics",
					"definition",
					"references",
					"document-symbols",
					"rename",
					"process-reuse",
					"shutdown",
				],
			},
			{
				platform: "linux",
				architecture: "x64",
				runner: "ubuntu-24.04",
				nodeVersion: "22.19.0",
				piVersion: "0.84.1",
				serverVersion: "5.3.0",
				languageVersion: "5.9.3",
				capabilities: [
					"diagnostics",
					"definition",
					"references",
					"document-symbols",
					"rename",
					"process-reuse",
					"shutdown",
				],
			},
		],
		manualHelp:
			"Install typescript-language-server and typescript, then retry.",
	},
];
